replicaCount: 1

image:
  repository: dathahi/du_an-frontend # Thay bằng tên image của bạn, ví dụ: myregistry/my-frontend
  pullPolicy: IfNotPresent
  tag: "1.0" # Hoặc tag cụ thể của image

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "js-front"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80 # Port mà frontend lắng nghe (thường là 80 cho ứng dụng web)

ingress:
  enabled: true # Bật Ingress để truy cập frontend từ bên ngoài
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: frontend.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
    # - secretName: frontend-tls
    #   hosts:
    #     - frontend.example.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# Cấu hình kết nối với backend
backend:
  host: "go-back" # Tên dịch vụ backend (khớp với fullnameOverride của backend)
  port: 3000
  apiBaseUrl: "http://backend.example.com" # URL để frontend gọi API backend

nodeSelector: {}
tolerations: []
affinity: {}
