ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: backend.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
    # - secretName: backend-tls
    #   hosts:
    #     - backend.example.com
